title: SoCraTesBE 2024 - PowerShell Playground
description: Base repository to start messing around with PowerShell + automated QA Implementations
remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
plugins:
  - jekyll-remote-theme